### ISSUE TITLE
Tor has already been shutdown exception

### ISSUE THREAD

**Issue by ManfredKarrer** [JesusMcCloud/netlayer#5]
When Bisq is shutting down we get that exception logged:
org.berndpruenster.netlayer.tor.TorCtlException: Tor has already been shutdown!
	at org.berndpruenster.netlayer.tor.Tor.getControl(Tor.kt:140)
	at org.berndpruenster.netlayer.tor.Tor.access$getControl$p(Tor.kt:132)
	at org.berndpruenster.netlayer.tor.Tor$1.run(Tor.kt:150)
	at java.lang.Thread.run(Thread.java:748)

Not sure if Bisq calls twice a shutdown or if in Netlayer the shutdown is called twice.

**Comment by JesusMcCloud** [comment]
Definitely a netlayer bug, thanks!

**Comment by JesusMcCloud** [comment]
Fixed in 0.3.3
